# Zawansowane Języki Programowania, 17/18

:experimental:
:imagesdir: ./images
:source-highlighter: pygments
:pygments-style: github
:icons: font

Literatura

. Greg Young, https://vimeo.com/108441214/description?__s=jvsvsq3unktoidfpqwzm[The art of destroying software], Vimeo
. Refactoring https://martinfowler.com/books/refactoringRubyEd.html[Ruby Edition],
  https://martinfowler.com/books/refactoring.html[Java Edition]
. http://helion.pl/ksiazki/czysty-kod-podrecznik-dobrego-programisty-robert-c-martin,czykov.htm#format/e[Czysty kod. Podręcznik dobrego programisty] (ebook)

Narzędzia

. Linters
. Code smell detectors (and brothers & sisters)
.. https://github.com/troessner/reek[reek] (for Ruby language)
.. https://github.com/bbatsov/rubocop[rubocop] – static code analyzer & style guide
.. https://github.com/seattlerb/flay[Flay] – analyzes code for structural similarities
. Editors
.. https://atom.io[Atom]


## The BDD micro-process

|===
| RED        | Write a new test and see it fail.
| GREEN      | Get all tests passing, using the most naive approach you can see.
| *REFACTOR* | Transition to the simplest design that passes the current tests,
               by removing any introduced smells.
| repeat     | Go around again.
|===

TODO: Insert picture HERE.


## Refactoring

Refactoring to technika bezpiecznego udoskonalania *istniejącego kodu*.
Innymi słowami, w trakcie refactoringu poprawiamy kod udoskonalając jego
wewnętrzną strukturę i nie zmieniając jego działania.

W trakcie refactoringu zmienia się nasze rozumienie cudzego kodu
Dlatego kod po refactoringu łatwiej jest łatwiejszy w zrozumieniu,
łatwiej go rozszerzać (szybciej piszemy nowy kod i robimy mniej błędów).


### Code smells ➨ Refactoring

Code smells suggest refactorings.

Probably, these refactorings are responsible for fixing the most smells:

. Move Method, Extract Class, Move Field, Extract Method

Quite a few refactorings are not mentioned by any of the smells.

[cols=">10s,25,65", options="header"]
|===
| # ^| Code Smell   ^| Refactorings

| 2+^e| Accommodating Change
| 2+^e| Conditional Logic
| 2+^e| Data
| 2+^e| Duplication
|     | Dervived Value  |
|     | Duplicated Code |
| 2+^e| Inheritance
|     | Repeated Value  |
| 2+^e| Libraries
| 2+^e| Measurable Smells
| 2+^e| Names
|     | Inconsistent Name    | j.w.
|     | Type Embeded in Name | Rename Method (or constant etc.)
|     | Uncommunicative Name | j.w.
| 2+^e| Responsibility
|   1 | Feature Envy           | Extract Method, Move Method, see Utility Function
|   2 | Global Variable        | Add Parameter
|     | Greedy Module          |
|     | Inappropriate Intimacy |
|     | Message Chain          |
|     | Middle Man             |
|   2 | Utility Function       | Extract Class
| 2+^e| Unnecessary Complexity
|===


### The refactoring cycle

```
start with working (tested) code
while the design can be simplified
  choose the worst smell
  select a refactoring that will address the smell
  apply the refactoring
  (check that tests still pass)
```

NOTE: This approach to refactoring does not guarantee to
get the ideal design, because you can not reach a global
maximum by looking at local properties.


## A refactoring example – _Hide Delegate_

TODO

## Wyszukiwanie code smells w kodzie

Automatyczne wyszukiwanie code smells w pliku za pomocą programu _reek_ –
https://github.com/troessner/reek[Code smell detector for Ruby].

.smelly.rb
[source,ruby]
----
# Smelly class
class Smelly
  # This will reek of UncommunicativeMethodName
  def x
    y = 10 # This will reek of UncommunicativeVariableName
  end
end
----

```sh
reek smelly.rb
Inspecting 1 file(s):
S

smelly.rb -- 2 warnings:
  [4]:UncommunicativeMethodName: Smelly#x has the name 'x' [https://github.com/troessner/reek/blob/master/docs/Uncommunicative-Method-Name.md]
  [5]:UncommunicativeVariableName: Smelly#x has the variable name 'y' [https://github.com/troessner/reek/blob/master/docs/Uncommunicative-Variable-Name.md]
```

Więcej przykładowych programów do wybróbowania z programem _reek_ można
znależć na http://www.codequizzes.com/ruby[Learn Ruby].

Można też spróbować swoich sił na zadaniach z portalu http://exercism.io[Exercism].

```sh
exercism list ruby
exercism fetch ruby hello-world
```
