# Zawansowane Języki Programowania, 17/18

:icons: font

Literatura

. Greg Young, https://vimeo.com/108441214/description?__s=jvsvsq3unktoidfpqwzm[The art of destroying software], Vimeo
. Refactoring https://martinfowler.com/books/refactoringRubyEd.html[Ruby Edition],
  https://martinfowler.com/books/refactoring.html[Java Edition]
. http://helion.pl/ksiazki/czysty-kod-podrecznik-dobrego-programisty-robert-c-martin,czykov.htm#format/e[Czysty kod. Podręcznik dobrego programisty] (ebook)

Narzędzia

. Linters
. Code smell detectors (and brothers & sisters)
.. https://github.com/troessner/reek[reek] (for Ruby language)
.. https://github.com/bbatsov/rubocop[rubocop] – static code analyzer & style guide
. Editors
.. https://atom.io[Atom]


## Refactoring (TODO)

Kod po refactoringu łatwiej zrozumieć i rozszerzać
(szybciej piszemy zaawansowany kod, robimy mniej błędów).

Jak?

. Usuwamy nadmiarowy kod.
. W trakcie refactoringu zmienia się nasze rozumienie cudzego kodu.
. Nie musimy pamiętać co stary kod robił.
. Piszemy kod szybciej.

TODO: A refactoring example: _Hide Delegate_.


## Code smells ➨ Refactoring

Code smell suggest refactoring. Examples of code smells:

. Move Method, Extract Class, Move Field, Extract Method

Quite a few refactorings are not mentioned by any of the smells
(unclear, duplicated, or unnecessary complicated code).

Automatyczne wyszukiwanie code smells w pliku za pomocą programu _reek_ –
https://github.com/troessner/reek[Code smell detector for Ruby].

.smelly.rb
[source,ruby]
----
# Smelly class
class Smelly
  # This will reek of UncommunicativeMethodName
  def x
    y = 10 # This will reek of UncommunicativeVariableName
  end
end
----

```sh
reek smelly.rb
Inspecting 1 file(s):
S

smelly.rb -- 2 warnings:
  [4]:UncommunicativeMethodName: Smelly#x has the name 'x' [https://github.com/troessner/reek/blob/master/docs/Uncommunicative-Method-Name.md]
  [5]:UncommunicativeVariableName: Smelly#x has the variable name 'y' [https://github.com/troessner/reek/blob/master/docs/Uncommunicative-Variable-Name.md]
```

Więcej przykładowych programów do wybróbowania z programem _reek_ można
znależć na http://www.codequizzes.com/ruby[Learn Ruby].

Można też spróbować swoich sił na zadaniach z portalu http://exercism.io[Exercism].

```sh
exercism list ruby
exercism fetch ruby hello-world
```
