# Extract Method
:source-highlighter: pygments
:pygments-style: pastie
:icons: font
:experimental:
:toc!:

## https://refactoring.guru/extract-method[Why]

## https://refactoring.guru/extract-method[Benefits]

## How to Refactor (Ruby Edition)

. Create a new method, and name it after the intention of the method.
. Copy the extracted code from the source method into the new target method.
. Scan the extracted code for references to any variables that are local in
scope to the source method. These are local variables and parameters to the
method.
. See whether any temporary variables are used only within this extracted code.
If so, declare them in the target method as temporary variables.
. Look to see whether any of these local-scope variables are modified by the
extracted code. If one variable is modified, see whether you can treat the
extracted code as a query and assign the result to the variable concerned.
You may need to use Split Temporary Variable and try again. You can eliminate
temporary variables with Replace Temp with Query.
. Pass into the target method as parameters local-scope variables that are read
from the extracted code.
. Replace the extracted code in the source method with a call to the target method.

## Examples

```ruby
def print_owing
  outstanding = 0.0
  # print banner # <1>
  puts "*************************"
  puts "***** Customer Owes *****"
  puts "*************************"
  # calculate outstanding # <3>
  @orders.each do |order|
    outstanding += order.amount
  end
  # print details # <2>
  puts "name: #{@name}"
  puts "amount: #{outstanding}"
end
```
<1> No local variable
<2> With local variable
<3> Reassigning a local variable


## No local variable

```ruby
def print_owing
  outstanding = 0.0
  print_banner
  # calculate outstanding
  @orders.each do |order|
    outstanding += order.amount
  end
  # print details
  puts "name: #{@name}"
  puts "amount: #{outstanding}"
end

def print_banner
  puts "*************************"
  puts "***** Customer Owes *****"
  puts "*************************"
end
```


## With local variable

.Step 1
```ruby
def print_owing
  outstanding = 0.0
  print_banner
  # calculate outstanding
  @orders.each do |order|
    outstanding += order.amount
  end
  # print details
  puts "name: #{@name}"
  puts "amount: #{amount}"
end

def print_details
end
```

.Step 2
```ruby
def print_owing(amount)
  outstanding = 0.0
  print_banner
  # calculate outstanding
  @orders.each do |order|
    outstanding += order.amount
  end
  puts "name: #{@name}"
  puts "amount: #{amount}"
end

def print_details
  puts "name: #{@name}"
  puts "amount: #{amount}"
end
```

.Step 3
```ruby
def print_owing(amount)
  outstanding = 0.0
  print_banner
  # calculate outstanding
  @orders.each do |order|
    outstanding += order.amount
  end
  puts "name: #{@name}"
  puts "amount: #{amount}"
end

def print_details(amount)
  puts "name: #{@name}"
  puts "amount: #{amount}"
end
```

.Step 7
```ruby
def print_owing(amount)
  outstanding = 0.0
  print_banner
  # calculate outstanding
  @orders.each do |order|
    outstanding += order.amount
  end
  print_details(amount)
end

def print_details(amount)
  puts "name: #{@name}"
  puts "amount: #{amount}"
end
```


## Reassigning a local variable

```ruby
def print_owing
  outstanding = 0.0
  print_banner
  # calculate outstanding
  @orders.each do |order|
    outstanding += order.amount
  end
  print_details(outstanding)
end
```

.Step 1
```ruby
def print_owing
  print_banner
  outstanding = calculate_outstanding
  print_details(outstanding)
end

def calculate_outstanding # <1>
  outstanding = 0.0
  @orders.each do |order|
    outstanding += order.amount
  end
  outstanding
end
```
<1> link:replace_loop_with_collection_closure_method.adoc[Replace Loop with Collection Closure Method]

```ruby
def print_owing
  print_banner
  outstanding = calculate_outstanding
  print_details(outstanding)
end

def calculate_outstanding
  @orders.inject(0.0) { |result, order| result + order.amount }
end
```
